import { mergeApplicationConfig, ApplicationConfig } from '@angular/core';
import { provideServerRendering } from '@angular/platform-server';
import { appConfig } from './app.config';

// generated by Angular for SSR configuration
// supplies server-specific providers (like node-based HTTP interop or SSR hydration configurations) that override
// or extend the standard app.config.ts during server-side compilation.
const serverConfig: ApplicationConfig = {
  providers: [
    provideServerRendering()
  ]
};

export const config = mergeApplicationConfig(appConfig, serverConfig);
